#!/usr/bin/env python3
"""Cross-platform full installer for Hermes Agent + Hermes Web UI.

Design goal: ask only two questions by default:
  1. install path
  2. agent/profile name

Everything else is detected, installed, or prepared automatically. Secrets such as
Telegram bot tokens are scaffolded but never requested or generated by this
installer.
"""
from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

REPO_URL_DEFAULT = "https://github.com/aihubos/ai-hub-os-hermes.git"
HERMES_UNIX_INSTALL = "https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh"
HERMES_WIN_INSTALL = "https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.ps1"
DEFAULT_PORT = 8788


def is_windows() -> bool:
    return platform.system().lower() == "windows"


def is_macos() -> bool:
    return platform.system().lower() == "darwin"


def is_wsl() -> bool:
    return platform.system().lower() == "linux" and "microsoft" in platform.release().lower()


def home() -> Path:
    return Path.home()


def default_install_path() -> Path:
    if is_windows():
        base = os.environ.get("LOCALAPPDATA") or str(home())
        return Path(base) / "HermesHub"
    return home() / "HermesHub"


def default_hermes_base() -> Path:
    if is_windows():
        # Native Hermes for Windows commonly uses LocalAppData, but ~/.hermes is
        # still safe if the upstream installer chooses it. This installer keeps
        # profile data in a predictable base and exports HERMES_HOME explicitly.
        base = os.environ.get("LOCALAPPDATA")
        if base:
            return Path(base) / "hermes"
    return home() / ".hermes"


def log(msg: str) -> None:
    print(f"[hermes-webui-install] {msg}", flush=True)


def warn(msg: str) -> None:
    print(f"[warning] {msg}", flush=True)


def die(msg: str, code: int = 1) -> None:
    print(f"[error] {msg}", file=sys.stderr, flush=True)
    raise SystemExit(code)


def run(cmd: list[str] | str, *, cwd: Path | None = None, env: dict[str, str] | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    printable = cmd if isinstance(cmd, str) else " ".join(cmd)
    log(f"run: {printable}")
    return subprocess.run(cmd, cwd=str(cwd) if cwd else None, env=env, text=True, shell=isinstance(cmd, str), check=check)


def capture(cmd: list[str], *, cwd: Path | None = None, env: dict[str, str] | None = None) -> tuple[int, str]:
    try:
        p = subprocess.run(cmd, cwd=str(cwd) if cwd else None, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
        return p.returncode, p.stdout.strip()
    except FileNotFoundError:
        return 127, ""


def sanitize_agent_name(raw: str) -> str:
    name = (raw or "default").strip().lower()
    name = re.sub(r"\s+", "-", name)
    name = re.sub(r"[^a-z0-9_-]", "-", name)
    name = re.sub(r"-+", "-", name).strip("-_")
    if not name:
        name = "default"
    if not re.match(r"^[a-z0-9][a-z0-9_-]{0,63}$", name):
        die("Agent name must become a profile-safe value: a-z, 0-9, dash, underscore, max 64 chars.")
    return name[:64]


def ask_path(prompt: str, default: Path) -> Path:
    answer = input(f"{prompt} [{default}]: ").strip()
    return Path(answer).expanduser() if answer else default


def ask_text(prompt: str, default: str) -> str:
    answer = input(f"{prompt} [{default}]: ").strip()
    return answer or default


def ensure_python() -> str:
    # Prefer the interpreter running this installer. It avoids Windows `py -3`
    # argument-shape surprises when creating venvs.
    current = Path(sys.executable)
    if current.exists():
        code, out = capture([str(current), "--version"])
        if code == 0:
            log(f"Python found: {current} ({out})")
            return str(current)
    candidates = ["python3", "python"] if not is_windows() else ["python", "python3"]
    for exe in candidates:
        code, out = capture([exe, "--version"])
        if code == 0:
            log(f"Python found: {exe} ({out})")
            return exe
    die("Python 3 was not found. Install Python 3.11+ first, then re-run this installer.")
    raise RuntimeError("unreachable")


def ensure_git() -> str:
    code, out = capture(["git", "--version"])
    if code == 0:
        log(f"Git found: {out}")
        return "git"
    # Some Windows Hermes installs may include a bundled git later, but cloning
    # this repo already normally required git. Keep message simple.
    if is_windows():
        die("Git was not found. Install Git for Windows, then re-run install.ps1.")
    if is_macos():
        die("Git was not found. Run `xcode-select --install`, then re-run install.sh.")
    die("Git was not found. Install git with your package manager, then re-run install.sh.")
    raise RuntimeError("unreachable")


def hermes_exists() -> bool:
    code, _ = capture(["hermes", "--help"])
    return code == 0


def install_hermes_agent() -> None:
    if hermes_exists():
        log("Hermes CLI already available.")
        return
    log("Hermes CLI not found. Installing Hermes Agent from official installer...")
    if is_windows():
        cmd = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", f"iex (irm {HERMES_WIN_INSTALL})"]
        run(cmd)
    else:
        # Do not use shell pipe from Python; download then execute for clearer errors.
        installer = Path.cwd() / ".hermes-agent-install.sh"
        urllib.request.urlretrieve(HERMES_UNIX_INSTALL, installer)
        installer.chmod(0o755)
        run(["bash", str(installer)])
    if not hermes_exists():
        warn("Hermes installer finished, but `hermes` is not on PATH in this shell yet.")
        warn("Open a new terminal after install, or add Hermes to PATH as shown by the official installer.")


def clone_or_update_repo(repo_url: str, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if (target / ".git").exists():
        log(f"Updating Web UI repo: {target}")
        run(["git", "-C", str(target), "pull", "--ff-only"])
        return
    if target.exists() and any(target.iterdir()):
        warn(f"Target exists and is not an empty git repo: {target}")
        warn("Using it as the current Web UI directory without cloning.")
        return
    log(f"Cloning Web UI repo into: {target}")
    run(["git", "clone", repo_url, str(target)])


def discover_agent_dir(hermes_base: Path, install_path: Path) -> Path | None:
    candidates = [
        os.environ.get("HERMES_WEBUI_AGENT_DIR"),
        str(hermes_base / "hermes-agent"),
        str(home() / ".hermes" / "hermes-agent"),
        str(install_path / "hermes-agent"),
        str(home() / "hermes-agent"),
    ]
    if is_windows() and os.environ.get("LOCALAPPDATA"):
        candidates.append(str(Path(os.environ["LOCALAPPDATA"]) / "hermes" / "hermes-agent"))
    for c in candidates:
        if not c:
            continue
        p = Path(c).expanduser()
        if (p / "run_agent.py").exists():
            return p.resolve()
    return None


def create_profile(hermes_base: Path, agent_name: str) -> Path:
    hermes_base.mkdir(parents=True, exist_ok=True)
    if agent_name == "default":
        profile_home = hermes_base
    else:
        profile_home = hermes_base / "profiles" / agent_name
        profile_home.mkdir(parents=True, exist_ok=True)
        (hermes_base / "active_profile").write_text(agent_name + "\n", encoding="utf-8")
    for d in ["memories", "sessions", "skills", "skins", "logs", "plans", "workspace", "cron", "webui_state"]:
        (profile_home / d).mkdir(parents=True, exist_ok=True)
    ensure_profile_env(profile_home)
    return profile_home


def append_if_missing(path: Path, marker: str, block: str) -> None:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if marker not in text:
        if text and not text.endswith("\n"):
            text += "\n"
        text += "\n" + block.strip() + "\n"
        path.write_text(text, encoding="utf-8")


def ensure_profile_env(profile_home: Path) -> None:
    env_path = profile_home / ".env"
    append_if_missing(
        env_path,
        "TELEGRAM_BOT_TOKEN",
        """
# Telegram Gateway 준비값
# 1) Telegram에서 @BotFather 로 봇을 만들고 토큰을 넣으세요.
# 2) @userinfobot 등으로 내 숫자 ID를 확인해 TELEGRAM_ALLOWED_USERS에 넣으세요.
TELEGRAM_BOT_TOKEN=
TELEGRAM_ALLOWED_USERS=
# TELEGRAM_HOME_CHANNEL=
""",
    )


def env_quote(value: Path | str) -> str:
    text = str(value).replace('\\', '\\\\').replace('"', '\\"')
    return f'"{text}"'


def write_webui_env(repo_dir: Path, hermes_base: Path, profile_home: Path, agent_dir: Path | None) -> None:
    env_path = repo_dir / ".env"
    lines = [
        "# Generated by install.py. Machine-local file; do not commit secrets here.",
        f"HERMES_HOME={env_quote(profile_home)}",
        f"HERMES_BASE_HOME={env_quote(hermes_base)}",
        "HERMES_WEBUI_HOST=127.0.0.1",
        f"HERMES_WEBUI_PORT={DEFAULT_PORT}",
        f"HERMES_WEBUI_STATE_DIR={env_quote(profile_home / 'webui_state')}",
        f"HERMES_WEBUI_DEFAULT_WORKSPACE={env_quote(profile_home / 'workspace')}",
        f"HERMES_CONFIG_PATH={env_quote(profile_home / 'config.yaml')}",
    ]
    if agent_dir:
        lines.append(f"HERMES_WEBUI_AGENT_DIR={env_quote(agent_dir)}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Wrote Web UI env: {env_path}")


def make_venv(repo_dir: Path, python_exe: str) -> Path:
    venv_dir = repo_dir / ".venv"
    if is_windows():
        venv_python = venv_dir / "Scripts" / "python.exe"
    else:
        venv_python = venv_dir / "bin" / "python"
    if not venv_python.exists():
        run([python_exe, "-m", "venv", str(venv_dir)], cwd=repo_dir)
    run([str(venv_python), "-m", "pip", "install", "--upgrade", "pip"], cwd=repo_dir)
    req = repo_dir / "requirements.txt"
    if req.exists():
        run([str(venv_python), "-m", "pip", "install", "-r", str(req)], cwd=repo_dir)
    return venv_python


def write_launchers(install_path: Path, repo_dir: Path, profile_home: Path) -> None:
    install_path.mkdir(parents=True, exist_ok=True)
    if is_windows():
        (install_path / "start-webui.ps1").write_text(
            f"$env:HERMES_HOME = '{profile_home}'\n"
            f"Set-Location '{repo_dir}'\n"
            f".\\start.ps1\n",
            encoding="utf-8",
        )
        (install_path / "start-gateway.ps1").write_text(
            f"$env:HERMES_HOME = '{profile_home}'\n"
            "hermes gateway run\n",
            encoding="utf-8",
        )
    else:
        start_web = install_path / "start-webui.sh"
        start_web.write_text(
            "#!/usr/bin/env bash\nset -euo pipefail\n"
            f"export HERMES_HOME={sh_quote(str(profile_home))}\n"
            f"cd {sh_quote(str(repo_dir))}\n"
            "./start.sh\n",
            encoding="utf-8",
        )
        start_gw = install_path / "start-gateway.sh"
        start_gw.write_text(
            "#!/usr/bin/env bash\nset -euo pipefail\n"
            f"export HERMES_HOME={sh_quote(str(profile_home))}\n"
            "hermes gateway run\n",
            encoding="utf-8",
        )
        start_web.chmod(0o755)
        start_gw.chmod(0o755)


def sh_quote(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def health_check(repo_dir: Path, venv_python: Path) -> bool:
    start_py = repo_dir / "start.py"
    if not start_py.exists():
        warn("start.py not found; skipping Web UI health check.")
        return False
    # `start.py --check` prepares deps and imports config without leaving a server running.
    code, out = capture([str(venv_python), str(start_py), "--check"], cwd=repo_dir)
    if out:
        print(out)
    return code == 0


def final_summary(install_path: Path, repo_dir: Path, hermes_base: Path, profile_home: Path, agent_name: str, agent_dir: Path | None, webui_ok: bool) -> None:
    print("\n========================================")
    print("Hermes full setup prepared")
    print("========================================")
    print(f"Install path : {install_path}")
    print(f"Agent name   : {agent_name}")
    print(f"Hermes base  : {hermes_base}")
    print(f"Profile home : {profile_home}")
    print(f"Web UI repo  : {repo_dir}")
    print(f"Agent dir    : {agent_dir or 'not discovered yet'}")
    print(f"Web UI check : {'ok' if webui_ok else 'needs manual start check'}")
    print("")
    print("Start Web UI:")
    if is_windows():
        print(f"  powershell -ExecutionPolicy Bypass -File {install_path / 'start-webui.ps1'}")
    else:
        print(f"  {install_path / 'start-webui.sh'}")
    print(f"  then open http://localhost:{DEFAULT_PORT}")
    print("")
    print("Telegram Gateway prepared, but token/user ID cannot be generated automatically.")
    print("Next manual secret step:")
    print(f"  edit {profile_home / '.env'}")
    print("  fill TELEGRAM_BOT_TOKEN and TELEGRAM_ALLOWED_USERS")
    print("  then run:")
    if is_windows():
        print(f"  powershell -ExecutionPolicy Bypass -File {install_path / 'start-gateway.ps1'}")
    else:
        print(f"  {install_path / 'start-gateway.sh'}")
    print("")
    if not hermes_exists():
        print("Note: Hermes CLI is not visible on PATH in this shell. Open a new terminal if the official installer updated PATH.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Install Hermes Agent + Hermes Web UI + Telegram Gateway prep")
    parser.add_argument("--install-path", type=Path, help="Install path. If omitted, prompt once.")
    parser.add_argument("--agent-name", help="Hermes profile/agent name. If omitted, prompt once.")
    parser.add_argument("--repo-url", default=REPO_URL_DEFAULT, help="Web UI git repository URL")
    parser.add_argument("--skip-hermes-install", action="store_true", help="Do not run the official Hermes Agent installer")
    parser.add_argument("--yes", action="store_true", help="Use defaults for any omitted prompt values")
    args = parser.parse_args()

    install_path = args.install_path.expanduser() if args.install_path else (default_install_path() if args.yes else ask_path("Install path", default_install_path()))
    agent_raw = args.agent_name if args.agent_name else ("default" if args.yes else ask_text("Agent name", "default"))
    agent_name = sanitize_agent_name(agent_raw)

    ensure_python()
    ensure_git()
    install_path.mkdir(parents=True, exist_ok=True)

    if not args.skip_hermes_install:
        install_hermes_agent()

    repo_dir = install_path / "ai-hub-os-hermes"
    current_repo = Path(__file__).resolve().parent
    # If install.py is run from an already cloned repo, use/update that repo
    # instead of cloning a nested copy into itself.
    if (current_repo / ".git").exists() and current_repo.name == "ai-hub-os-hermes":
        repo_dir = current_repo
        log(f"Using current Web UI repo: {repo_dir}")
    else:
        clone_or_update_repo(args.repo_url, repo_dir)

    hermes_base = default_hermes_base()
    profile_home = create_profile(hermes_base, agent_name)
    agent_dir = discover_agent_dir(hermes_base, install_path)
    write_webui_env(repo_dir, hermes_base, profile_home, agent_dir)

    python_exe = ensure_python()
    venv_python = make_venv(repo_dir, python_exe)
    write_launchers(install_path, repo_dir, profile_home)
    webui_ok = health_check(repo_dir, venv_python)
    final_summary(install_path, repo_dir, hermes_base, profile_home, agent_name, agent_dir, webui_ok)


if __name__ == "__main__":
    main()
